spring:
  application:
    name: ecom

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomDb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
